ocs/ocs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('provider/', include('provider.urls')),
    path('franchise/', include('franchise.urls')),
    path('products/', include('products.urls')),
    path('accounts/', include('accounts.urls')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

ocs/provider/urls.py
"""
created by:     Django
description:    This are the paths of the providers app to show in the browser
                This paths lead to our views
modify by:      Alberto
modify date:    25/10/18
"""

from django.urls import path, include
from . import views

app_name = 'provider'
urlpatterns = [
    path('register/', views.registerProvider, name='register'),
    path('home/', views.home, name='home'),
    path('my_clients/', views.my_clients, name='my_clients'),
    path('my_clients/link_code/', views.link_code, name='link_code'),
    path('office/', views.office, name='office'),
    path('office/<int:id_day_hour>/', views.office_assign, name='office_assign'),
    path('my_clients/<int:id_franchise>/', views.client_detail, name='client_detail'),
    path('my_clients/daily_clients/', views.daily_clients, name='daily_clients'),
    path('my_clients/daily_clients_interactive/', views.daily_clients_interactive, name='daily_clients_interactive'),
    path('profile/', views.profile, name="profile"),
    path('profile/edit/', views.edit_provider, name="editProfile"),
    path('excel/', views.excel, name="excel"),
]

ocs/provider/models.py
"""
created by:     Django
description:    This are our models (db tables) that help us with data control
modify by:      Alberto
modify date:    26/10/18
"""

import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from franchise.models import Franchise

class Provider(models.Model):
    razon_social = models.CharField(max_length=200)
    rfc = models.CharField(max_length=13)
    nombre = models.CharField(max_length=100)
    domicilio = models.TextField(max_length=200)
    mision = models.TextField(max_length=4000)
    vision = models.TextField(max_length=4000)
    activo = models.BooleanField()
    fecha_registro = models.DateTimeField('date published')
    id_usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.rfc

class LinkWithF(models.Model):
    id_provider = models.ForeignKey(Provider, on_delete=models.CASCADE, blank=True, null=True)
    id_franchise = models.ForeignKey(Franchise, on_delete=models.CASCADE, blank=True, null=True)
    link_code = models.CharField(max_length=12)
    active = models.BooleanField()
    used = models.BooleanField()
    is_daily_client = models.BooleanField()
    date_of_creation = models.DateTimeField(default=timezone.now, blank=True)
    def check_timeout(self):
        if (timezone.now() - self.date_of_creation) > datetime.timedelta(days=5):
            return True
        return False

class Days(models.Model):
    nombre = models.CharField(max_length = 100)
    def __str__(self):
        return self.nombre

class OfficeHours(models.Model):
    id_provider = models.ForeignKey(Provider, on_delete=models.CASCADE, blank=True, null=True)
    day = models.ForeignKey(Days, on_delete=models.CASCADE, blank=True, null=True)
    start_hour = models.TimeField()
    finish_hour = models.TimeField()

class DailyClients(models.Model):
    id_provider = models.ForeignKey(Provider, on_delete=models.CASCADE, blank = True, null = True)
    id_franchise = models.ForeignKey(Franchise, on_delete=models.CASCADE, blank = True, null = True)
    day = models.ForeignKey(Days, on_delete = models.CASCADE, blank = True, null = True)
    activo = models.BooleanField()

ocs/provider/forms.py
"""
created by:     Django
description:    This are the forms we use to providers
modify by:      Alberto
modify date:    26/10/18
"""

from django import forms
from django.utils import timezone

from provider.models import Provider
from accounts.models import OCSUser
from django.contrib.auth.models import User, Group

class RegisterProviderForm(forms.Form):

    razon_social = forms.CharField(label='Razón social',max_length=200,
        widget=forms.Textarea(
            attrs={
                'class':'form-control',
                'rows':'2',
            }))
    rfc = forms.CharField(label='RFC', max_length=13,
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
            }))
    nombre = forms.CharField(label='Nombre', max_length=100,
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
            }))
    domicilio = forms.CharField(label='Domicilio', max_length=200,
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
            }))
    mision = forms.CharField(label='Misión', max_length=4000,
        widget=forms.Textarea(
            attrs={
                'class':'form-control',
                'rows':'3',
            }))
    vision = forms.CharField(label='Visión', max_length=4000,
        widget=forms.Textarea(
            attrs={
                'class':'form-control',
                'rows':'3',
            }))
    #input, desc, output
    def process_registration(self, user):
        u = user
        ocsu = OCSUser.objects.get(user = user)
        p = Provider(razon_social=self.data['razon_social'],
                        rfc=self.data['rfc'],
                        nombre=self.data['nombre'],
                        domicilio=self.data['domicilio'],
                        mision=self.data['mision'],
                        vision=self.data['vision'],
                        activo=True,
                        fecha_registro=timezone.now(),
                        id_usuario=user)
        p.save()
        ocsu.id_provider = p
        ocsu.save()
        g = Group.objects.get(name="Administrador de empresa")
        g.user_set.add(u)
        g.save()
        return p

ocs/provider/views.py
"""
created by:     Django
description:    This are the views of the providers that helps their tasks
                to accomplish
modify by:      Fatima
modify date:    12/11/18
"""

from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.http import Http404, JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from datetime import datetime, timedelta


from accounts.models import *
from franchise.models import *
from inventory.models import *
from orders.models import *
from products.models import *
from provider.models import *

import xlwt
import string
import random

# Function that generates a random code of 12 characters
def code_generator(size=12, chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))

# Function that registers a new provider
@login_required
def registerProvider(request):
    # If POST then register provider
    if request.method == 'POST':
        register_form = RegisterProviderForm(request.POST)
        if register_form.is_valid():
            provider = register_form.process_registration(request.user)
            days_list = Days.objects.all()
            ##Inicia - Asigna horas de oficina por default
            for item in days_list:
                insert = OfficeHours(start_hour = "8:00", finish_hour = "18:00", day = item, id_provider = provider)
                insert.save()
            ##Termina
            return redirect('/accounts/locate/')
    # If not POST then show registration form
    else:
        u = OCSUser.objects.get(user = request.user)
        if u.id_provider!=None:
            return redirect('../provider/home')
        elif u.id_provider==None and (u.id_franchise!=None):
            return redirect('../franchise/home')
        else:
            register_form = RegisterProviderForm()
            return render(request, 'provider/register.html', {'register_form': register_form})

# Function that shows the homepage of provider
@login_required
def home(request):
    u = OCSUser.objects.get(user = request.user)
    if u.id_provider!=None:
        # Show provider home
        return render(request, 'provider/home.html', {'usuario':u,})
    else:
        # Redirect to other home
        return redirect('../')

@login_required
def link_code(request):
    """
     Function used to generate a random code to link with a franchise
     INPUT
        - Request method with the values of the session & the values
          sended by a POST method
     OUTPUT
        - A random code already saved in the database
    """
    u = OCSUser.objects.get(user = request.user)
    code = ''
    francs = LinkWithF.objects.filter(id_provider = u.id_provider, used = False)
    if request.method == 'POST':
        code = code_generator()
        l = LinkWithF(link_code=code, used=False, active=False)
        try:
            lTest = LinkWithF.objects.get(link_code=code)
        except:
            l.id_provider=u.id_provider
            l.save()
        else:
            link_code(request)
    return render(request, 'link_code/generate_link.html', {
            'usuario' : u,
            'code' : code,
            'francs' : francs,
            })

#Función para asignar horas de oficina a la empresa de lado proveedor
@login_required
def office_assign(request, id_day_hour):
    u = OCSUser.objects.get(user = request.user)
    prov = u.id_provider_id
    provider = Provider.objects.get(id = prov)
    days_hour = OfficeHours.objects.get(id = id_day_hour)
    hours_list = OfficeHours.objects.filter(id_provider = provider)
    prov = Group.objects.get(name = "Administrador de empresa")
    user = request.user
    if request.method == 'POST' and (prov in user.groups.all()):
        #En lugar de añadir más filas a la tabla, sólo se editan las ya existentes
        days_hour.start_hour = request.POST["s_hour"]
        days_hour.finish_hour = request.POST["f_hour"]
        days_hour.save()

        return render(request, 'provider/office_main.html', {'hours_list': hours_list, 'usuario':u})

    #Only owners can perform the action
    if (prov in user.groups.all()):
        return render(request, 'provider/office.html', {'days_hour':days_hour, 'usuario':u})
    else :
        return redirect('../')

@login_required
def office(request):
    u = OCSUser.objects.get(user = request.user)
    prov = u.id_provider_id
    provider = Provider.objects.get(id = prov)
    hours_list = OfficeHours.objects.filter(id_provider = provider)
    prov = Group.objects.get(name = "Administrador de empresa")
    user = request.user

    #Only owners can perform the action
    if (prov in user.groups.all()):
        return render(request, 'provider/office_main.html', {'hours_list': hours_list, 'usuario':u})
    else :
        return redirect('../')


@login_required
def my_clients(request):
    empty_list = 0
    u = OCSUser.objects.get(user = request.user)
    relation_list = LinkWithF.objects.filter(id_provider=u.id_provider.id, active=True)
    if len(relation_list) == 0:
        empty_list = 1
    return render(request, 'my_clients/consult_clients.html', {'usuario' : u,'relation_list' : relation_list,'empty_list' : empty_list})

# Function that shows the provider its client detail
@login_required
def client_detail(request, id_franchise):
    success = True
    u = OCSUser.objects.get(user = request.user)
    F = Franchise()
    relation_list = LinkWithF.objects.filter(id_provider=u.id_provider, id_franchise=id_franchise)
    try:
        f = Franchise.objects.get(id=id_franchise)
        if len(relation_list) == 0:
            success = False
    except:
        success = False
    return render(request, 'my_clients/client_detail.html', {'usuario' : u,'success' : success,'franchise' : f,})

#Función para desplegar y añadir los clientes diarios de una empresa del lado de proveedor
@login_required
def daily_clients(request):
    user = request.user
    u = OCSUser.objects.get(user = user)
    prov = u.id_provider
    #provider = Provider.objects.get(id = prov.id)
    group_prov = Group.objects.get(name = "Administrador de empresa")

    #Selecciona la lista de los días
    days_list = Days.objects.all()

    lun = Days.objects.get(nombre="Lunes")
    lunes = DailyClients.objects.values_list('id_franchise', flat=True).filter(id_provider = prov, day = lun, activo=True)
    mar = Days.objects.get(nombre="Martes")
    martes = DailyClients.objects.values_list('id_franchise', flat=True).filter(id_provider = prov, day = mar, activo=True)
    mie = Days.objects.get(nombre="Miércoles")
    miercoles = DailyClients.objects.values_list('id_franchise', flat=True).filter(id_provider = prov, day = mie, activo=True)
    jue = Days.objects.get(nombre="Jueves")
    jueves = DailyClients.objects.values_list('id_franchise', flat=True).filter(id_provider = prov, day = jue, activo=True)
    vie = Days.objects.get(nombre="Viernes")
    viernes = DailyClients.objects.values_list('id_franchise', flat=True).filter(id_provider = prov, day = vie, activo=True)
    sab = Days.objects.get(nombre="Sábado")
    sabado = DailyClients.objects.values_list('id_franchise', flat=True).filter(id_provider = prov, day = sab, activo=True)
    dom = Days.objects.get(nombre="Domingo")
    domingo = DailyClients.objects.values_list('id_franchise', flat=True).filter(id_provider = prov, day = dom, activo=True)

    #Se hace un filtro para desplegar solo los clientes ligados con ese usuario proveedor
    clients_list = LinkWithF.objects.filter(id_provider = prov, active=True)

    data = {    'usuario':u,
                'clients_list': clients_list,
                'days_list':days_list,
                'lunes':lunes,
                'martes':martes,
                'miercoles':miercoles,
                'jueves':jueves,
                'viernes':viernes,
                'sabado':sabado,
                'domingo':domingo,
                }
    if request.method == 'POST' and (group_prov in user.groups.all()):
        #Hace el registro
        obj_prov = prov
        obj_fran = Franchise.objects.get( nombre = request.POST['client'])
        obj_day = Days.objects.get(nombre = request.POST['day'])
        link = LinkWithF.objects.get(id_provider = obj_prov, id_franchise=obj_fran, active=True)
        daily_clients = DailyClients.objects.filter(id_provider = prov, activo=True)
        aux = False
        for d in daily_clients:
            if d.id_franchise == obj_fran and d.day == obj_day:
                aux = True
                messages.warning(request, '¡Esa relación ya existe!')
        if aux is False:
            register = DailyClients(id_provider = obj_prov, id_franchise = obj_fran, day = obj_day, activo = True)
            register.save()
            link.is_daily_client = True
            link.save()
            messages.success(request, 'Tu cliente ya te podrá pedir estos días...')
        #Fin de registro
        return redirect(reverse('provider:daily_clients'))
    if (group_prov in user.groups.all()):
        return render(request, 'my_clients/daily_clients.html', data)
    else:
        return redirect('../')

def daily_clients_interactive(request):
    user = request.user
    u = OCSUser.objects.get(user = user)
    prov = u.id_provider
    id_franchise = request.GET.get('id_franchise', None)
    day = request.GET.get('day', None)
    add = request.GET.get('add', None)
    if id_franchise is not None and day is not None and add is not None:
        obj_prov = prov
        obj_fran = Franchise.objects.get(id = id_franchise)
        obj_day = Days.objects.get(id = day)
        link = LinkWithF.objects.get(id_provider = obj_prov, id_franchise=obj_fran, active=True)

ocs/provider/templates/provider/base.html
{% load static %}
<!DOCTYPE html>
<head lang="es">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}OCS{% endblock title %}</title>
  <link rel="icon" type="image/png" href="{% static 'OCS.png' %}">
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" ></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static 'provider/style.css' %}">

</head>
<body onload="initialize()">
  <div id="navbar">
    {% block navbar %}
    {% endblock navbar %}
  </div>
  <div id="wrapper" class="toggled" >
    <div id="sidebar-wrapper" style="background-color:rgb(37,42,48)">
      <div id="sidebar">
        {% block sidebar %}
        {% endblock sidebar %}
      </div>
    </div>
    <div id="page-content-wrapper">
        <div class="container-fluid">
          <div id="content" style="margin-top:54px">
            {% if messages %}
                {% for message in messages %}
                  <div class="alert alert-{% if message.tags %}{{ message.tags }}{% else %}danger{% endif %} alert-dismissible fade show" role="alert">
                    <strong>{{ message }}</strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                {% endfor %}
            {% endif %}
            {% block content %}
            {% endblock content %}
          </div>
        </div>
    </div>
  </div>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
  <script type="text/javascript" src="{% static 'js/provider.js' %}"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" charset="utf8"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>

<footer>
  {% block footer %}
  {% endblock footer %}
</footer>

ocs/provider/templates/provider/home.html
{% extends "provider/base.html" %}
{% block title %}OCS - {{usuario.id_provider.nombre}}{% endblock title %}

{% block navbar %}
<nav class="navbar navbar-dark fixed-top" style="background-color:rgb(53,108,153)">
  <a class="navbar-brand" href="{% url 'home' %}">{{usuario.id_provider.nombre}}</a>
  <ul class="navbar-nav px-3">
    <div class="row">
      <li class="nav-item">
        <div class="popup" onclick="popUP()">
          <a class="nav-link"><span class="fa fa-user-circle" style="font-size:20px"></span>&emsp;{{usuario.user.first_name}} {{usuario.user.last_name}}</a>
          <div class="popuptext shadow" id="myPopup">
            <div class="list-group">
              <a href="/accounts/profile/" class="list-group-item list-group-item-action">
                <span class="fa fa-user"></span> Mi perfil
              </a>
              <a href="/provider/profile/" class="list-group-item list-group-item-action">
                <span class="fa fa-industry"></span> {{usuario.id_provider.nombre}}
              </a>
            </div>
          </div>
        </div>
      </li>
      &emsp;&emsp;&emsp;&emsp;&emsp;
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}"><span class="fa fa-sign-out"></span> Cerrar sesión</a>
      </li>
    </div>
  </ul>
</nav>
{% endblock navbar %}

{% block sidebar %}
<ul class="sidebar-nav">
    <li class="sidebar-brand"></li>
    <li><a href="/provider/home/"><span class="fa fa-home"></span> Inicio</a></li>
    <li><a href="/orders/consult_orders/"><span class="fa fa-fax"></span> Pedidos</a></li>
    <li><a href="/accounts/myEmployees/"><span class="fa fa-users"></span> Usuarios</a></li>
    <li><a href="/products/myProducts/"><span class="fa fa-book"></span> Catálogo</a></li>
    <li><a href="/provider/my_clients/"><span class="fa fa-handshake-o"></span> Clientes</a></li>
    <li><a href="/provider/office/"><span class="fa fa-cog"></span> Configuración</a></li>
    <!--<li><a href="#">About</a></li>
    <li><a href="#">Services</a></li>
    <li><a href="#">Contact</a></li>-->
</ul>
{% endblock sidebar %}

{% block content %}
  {% block extras %}
  <h4>Exportar concentrado de pedidos del día de mañana...</h4>
  <hr>
  <form action="/provider/excel/" method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary"><span class="fa fa-file-excel-o"> </span> </button> <small> testing</small>
  </form>
  {% endblock extras %}


{% endblock content %}

{% block footer %}
<script>
function popUP() {
    var popup = document.getElementById("myPopup");
    popup.classList.toggle("show");
}
</script>
{% endblock footer %}

ocs/provider/templates/provider/office.html
<!--
"""
Description: HTML view for the office daily schedule
Modified by: Fátima
Modify date: 20-10-18
"""
-->
{% extends "provider/home.html" %}
{% block title %}OCS - Registro de Horario de Oficina{% endblock title %}


{% block content %}

<div class="clearfix">
  <h3 class="float-left">
    Horario de oficina
  </h3>
  <h3 class="float-right">
  </h3>
</div>

<hr />

  <div class="container">
    <p>Asigna las horas en las que tu empresa va a operar</p><br>
    <div class='container'>
      <div class='row'>
        <div class="col">
          <form method="post">
          {% csrf_token %}
          <div class="form-group row">
            <div class="col-1">
            <strong>{{ days_hour.day.nombre }}</strong>
            </div>
            <div class="col-3">
              <label for="s_hour">Hora inicio</label>
              <input class="form-control" type="time" value="12:00" name="s_hour" id="s_hour">
            </div>
            <div class="col-3">
              <label for="f_hour">Hora fin</label>
              <input class="form-control" type="time" value="12:00" name="f_hour" id="f_hour">
            </div>
            <div class="col-3 mt-4">
              <button type="submit" class="btn btn-md btn-primary">Registrar horas</button>
            </div>
            <div class="col-2 mt-4">
              <a class="btn btn-danger" href="/provider/office">Cancelar</a>
            </div>
          </div>
          <br><hr>

          </form>
          <br><br><br>
        </div>
      </div>
    </div>

  </div>

{% endblock content%}

ocs/provider/templates/provider/office_main.html
<!--
"""
Description: HTML view for the office daily schedule
Modified by: Fátima
Modify date: 12-11-18
"""
-->
{% extends "provider/home.html" %}
{% block title %}OCS - Registro de Horario de Oficina{% endblock title %}


{% block content %}
<div class="clearfix">
  <h3 class="float-left">
    Horario de oficina
  </h3>
  <h3 class="float-right">
  </h3>
</div>

<hr />

  <div class="container">
    <div class='container'>
      <div class='row'>
        <div class="col border rounded">
          <table class="table table-responsive-xl table-hover table-sm mx-1">
            <thead>
              <tr>
                <th scope="col">Día</th>
                <th scope="col">Hora de Apertura</th>
                <th scope="col">Hora de Cierre</th>
                <th scope="col">Opciones</th>
              </tr>
            </thead>
            <tbody id="consult_orders">
              {% for item in hours_list %}
              <tr>
                <td>{{item.day.nombre}}</td>
                <td>{{item.start_hour}}</td>
                <td>{{item.finish_hour}}</td>
                <td>
                  <a href="/provider/office/{{ item.id }}">
                  <button type="button" class="btn btn-primary" name="button" onclick="">
                    Editar hora
                  </button>
                  </a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>


        </div>
      </div>
    </div>

  </div>

{% endblock content%}

ocs/provider/templates/provider/profile.html
{% extends "provider/home.html" %}
{% block content %}
<br>
<div class="row">
  <div class="col">
    <div class="jumbotron">
      {% if edit %}
      <form method="post" action="{% url 'provider:editProfile' %}">
        {% csrf_token %}
        <div class="form-group">
          <label for="nombre">Nombre:</label>
          <input id="nombre" name="nombre" type="text" class="form-control" max_length=100 required value="{{ usuario.id_provider.nombre }}">
        </div>
        <div class="form-group">
          <label for="razon_social">Razón social:</label>
          <input id="razon_social" name="razon_social" type="text" class="form-control" max_length=200 required value="{{ usuario.id_provider.razon_social }}">
        </div>
        <div class="form-group">
          <label for="rfc">RFC:</label>
          <input id="rfc" name="rfc" type="text" class="form-control" max_length=13 required value="{{ usuario.id_provider.rfc }}">
        </div>
        <div class="form-group">
          <label for="domicilio">Domicilio:</label>
          <input id="domicilio" name="domicilio" type="text" class="form-control" max_length=200 required value="{{ usuario.id_provider.domicilio }}">
        </div>
        <div class="form-group">
          <label for="mision">Misión:</label>
          <textarea id="mision" name="mision" type="text" class="form-control" max_length=4000 required>{{ usuario.id_provider.mision }}</textarea>
        </div>
        <div class="form-group">
          <label for="vision">Visión:</label>
          <textarea id="vision" name="vision" type="text" class="form-control" max_length=4000 required>{{ usuario.id_provider.vision }}</textarea>
        </div>
        <center>
          <div class="btn-group btn-lg" role="group" aria-label="Basic example">
            <a class="btn btn-danger" href="{% url 'provider:profile' %}" role="button">Cancelar</a>
            <button type="submit" class="btn btn-success">Actualizar información!</button>
          </div>
        </center>
      </form>
      {% else %}
      <div class="text-center">
        <h1>{{ usuario.id_provider.nombre }}</h1>
        <h4>{{ usuario.id_provider.razon_social }}</h4>
        <h4>{{ usuario.id_provider.rfc }}</h4>
        <h4>{{ usuario.id_provider.domicilio }}</h4>
        <h4>{{ usuario.id_provider.mision }}</h4>
        <h4>{{ usuario.id_provider.vision }}</h4>
        <h4>{{ usuario.id_provider.activo }}</h4>
        <a class="btn btn-warning" href="{% url 'provider:editProfile' %}" role="button">
          <span class="fa fa-edit"></span> Editar
        </a>
      </div>
      {% endif %}
    </div>
  </div>
  <div class="col" style="max-width:200px">
  </div>
</div>
{% endblock content %}

ocs/provider/templates/provider/register.html
{% extends "home/index.html" %}
{% load static %}


{% block title %}OCS - Registro de proveedor{% endblock title %}

{% block content %}
<div class='container' style='max-width:750px'>
  <br><br>
  <center><img class="" src="{% static 'OCS.png' %}" alt="OCS"></center>
  <form action="{% url 'provider:register' %}" method="post">
    {% csrf_token %}
    {% for field in register_form %}
    <div class='form-group'>
      <label for="{{ field.name }}">{{ field.label }}</label>
      {{ field }}
    </div>
    {% endfor %}
    <br>
    <center><button type="submit" class="btn btn-success btn-lg btn-block">Registrar proveedor</button></center>
  </form>
  {{ Success_mesage }}
</div>
<br><br>
{% endblock content %}

{% block footer %}
{% endblock footer %}