ocs/ocs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('provider/', include('provider.urls')),
    path('franchise/', include('franchise.urls')),
    path('products/', include('products.urls')),
    path('accounts/', include('accounts.urls')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

ocs/products/urls.py
"""
created by:     Django
description:    This are the paths that are shown in the browser
                while interacting with products
modify by:      Alberto
modify date:    04/11/18
"""
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'products'
urlpatterns = [
    path('myProducts/', views.my_products, name='myProducts'),
    path('register/', views.registerProduct, name='register'),

    # FUNCIONES DE AJAX
    path('able_unable_product/', views.able_unable_product, name='able_unable_product'),
    path('get_product/', views.get_product_info, name='get_product'),
    path('edit/', views.edit_product, name='edit'),
    path('get_product_price/', views.get_product_price, name='get_product_price'),
    path('check_unidad/', views.check_unidad, name='check_unidad'),
    path('add_price/', views.add_price, name='add_price'),
    path('save_price/', views.save_price, name='save_price'),
    path('delete_price/', views.delete_price, name='delete_price'),

    path('get_product_equiv/', views.get_product_equiv, name='get_product_equiv'),
    path('add_equivalencia/', views.add_equivalencia, name='add_equivalencia'),

    path('delete_equiv/', views.delete_equiv, name='delete_equiv'),
    path('check_equiv_destino/', views.check_equiv_destino, name='check_equiv_destino'),

    #AJAX FOR ORDERS
    path('check_available_product/', views.check_available_product, name='check_available_product'),
]

ocs/products/models.py
"""
created by:     Django
description:    This are the models of the db
modify by:      Alberto
modify date:    04/11/18
"""
# Create your models here.
import datetime
from django.db import models
from django.utils import timezone
from provider.models import Provider
from franchise.models import Franchise



class Product(models.Model):
    id_provider = models.ForeignKey(Provider, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=200)
    codigo = models.CharField(max_length=10)
    activo = models.BooleanField()
    fecha_registro = models.DateTimeField('date published')
    def __str__(self):
        return self.nombre

class Price(models.Model):
    id_product = models.ForeignKey(Product, on_delete=models.CASCADE)
    fecha_inicio = models.DateTimeField('date published')
    fecha_final = models.DateTimeField(null=True)
    cantidad = models.DecimalField(max_digits=6 ,decimal_places=2)
    activo = models.BooleanField()

class UnidadDeMedida(models.Model):
    nombre =  models.CharField(max_length=20)
    abreviacion = models.CharField(max_length=10)

class CompleteProduct(models.Model):
    id_product = models.ForeignKey(Product, on_delete=models.CASCADE)
    id_unidad = models.ForeignKey(UnidadDeMedida, on_delete=models.CASCADE)
    id_price = models.ForeignKey(Price, on_delete=models.CASCADE)
    activo = models.BooleanField()

class Equivalencias(models.Model):
    id_product = models.ForeignKey(Product, on_delete=models.CASCADE)
    id_unidad_origen = models.ForeignKey(UnidadDeMedida, on_delete=models.CASCADE, related_name='id_unidad_origen')
    cantidad_origen = models.DecimalField(max_digits=6 ,decimal_places=2, default=1)
    id_unidad_destino = models.ForeignKey(UnidadDeMedida, on_delete=models.CASCADE, related_name='id_unidad_destino')
    cantidad_destino = models.DecimalField(max_digits=6 ,decimal_places=2)
    activo = models.BooleanField()








#

ocs/products/views.py
"""
created by:     Django
description:    This are the views used to work with products
modify by:      Alberto
modify date:    04/11/18
"""
# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.http import Http404, JsonResponse
import json

from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib import messages
from decimal import Decimal

from accounts.models import *
#from franchise.models import *
#from inventory.models import *
#from orders.models import *
from products.models import *
from provider.models import *


# INPUT
# OUTPUT
# Function that shows the provider its products
def my_products(request):
    u = OCSUser.objects.get(user = request.user)
    prov = Provider.objects.get(id = u.id_provider.id)
    prod = Product.objects.filter(id_provider = prov.id).order_by('-id')
    unidad = UnidadDeMedida.objects.all()
    return render(request, 'products/my_products.html', {'usuario':u, 'productos':prod,'unidad':unidad,})

# Function that let the provider register a new product
def registerProduct(request):
    u = OCSUser.objects.get(user = request.user)
    if request.POST['nombre'] == '' or request.POST['descripcion'] == '' or request.POST['codigo'] == '':
        messages.warning(request, 'Necesitas llenar todos los campos!')
    else:
        if request.POST.get('activo', '') == 'on':
            aux = True
        else:
            aux = False
        p = Product(id_provider=u.id_provider,
                        nombre=request.POST['nombre'].lower(),
                        descripcion=request.POST['descripcion'],
                        codigo=(request.POST['codigo']).upper(),
                        activo= aux,
                        fecha_registro=timezone.now())
        prod1 = Product.objects.filter(nombre=p.nombre, id_provider=p.id_provider)
        prod2 = Product.objects.filter(codigo=p.codigo, id_provider=p.id_provider)
        if not prod1 and not prod2:
            p.save()
            if request.POST['precio']!=0 and request.POST.get('unidad_medida',0)!=0:
                unidad = UnidadDeMedida.objects.get(id=request.POST['unidad_medida'])
                price = Price(id_product = p,fecha_inicio = timezone.now(), cantidad = request.POST['precio'], activo = True)
                price.save()
                complete = CompleteProduct(id_product=p, id_unidad=unidad, id_price=price, activo=True)
                complete.save()
            messages.success(request, 'Producto registrado!')
        else:
            if prod1 and prod2:
                messages.warning(request, 'El nombre y el código asignados ya existen')
            elif prod2:
                messages.warning(request, 'El código asignado ya existe')
            else:
                messages.warning(request, 'El nombre asignado ya existe')
    return redirect(reverse('products:myProducts'))


# AJAX FUNCTIONS
def able_unable_product(request):
    id_product = request.GET.get('id_product', None)
    p = Product.objects.get(id = id_product)
    if p.activo:
        p.activo = False
    else:
        p.activo = True
    p.save()
    data = {
        'able': p.activo,
    }
    return JsonResponse(data)
def get_product_info(request):
    id_product = request.GET.get('id_product', None)
    product = Product.objects.get(id=id_product)
    data = {
        'id_product': product.id,
        'nombre': product.nombre,
        'descripcion': product.descripcion,
        'codigo': product.codigo,
        'activo': product.activo,
    }
    return JsonResponse(data)
def edit_product(request):
    u = OCSUser.objects.get(user = request.user)
    p = Product.objects.get(id = request.POST['id_product'])
    prov = Provider.objects.get(id = u.id_provider.id)
    prod = Product.objects.filter(id_provider = prov.id)
    # If POST then make validations and save product info
    if request.method == 'POST':
        if request.POST['nombre'] == '' or request.POST['descripcion'] == '' or request.POST['codigo'] == '':
            messages.warning(request, 'Necesitas llenar todos los campos!')
        else:
            if request.POST.get('activo', '') == 'on':aux = True
            else:aux = False
            p = Product.objects.get(id=request.POST['id_product'])
            prod1 = Product.objects.filter(nombre=request.POST['nombre'].lower(), id_provider=p.id_provider).exclude(id=request.POST['id_product'])
            prod2 = Product.objects.filter(codigo=request.POST['codigo'].upper(), id_provider=p.id_provider).exclude(id=request.POST['id_product'])
            if not prod1 and not prod2:
                p.nombre=request.POST['nombre'].lower()
                p.descripcion=request.POST['descripcion']
                p.codigo=request.POST['codigo'].upper()
                p.activo= aux
                p.save()
                messages.success(request, 'La información se actualizó con éxito!')
                return redirect(reverse('products:myProducts'))
            else:
                auxp = Product(id=p.id,
                                id_provider=u.id_provider,
                                nombre=request.POST['nombre'],
                                descripcion=request.POST['descripcion'],
                                codigo=request.POST['codigo'],
                                activo= aux)
                if prod1 and prod2:
                    messages.warning(request, 'El nombre y el código asignados ya existen')
                    auxp.nombre = ''
                    auxp.codigo = ''
                elif prod2:
                    messages.warning(request, 'El código asignado ya existe')
                    auxp.codigo = ''
                else:
                    messages.warning(request, 'El nombre asignado ya existe')
                    auxp.nombre = ''
                return render(request, 'products/my_products.html', {'usuario':u,'producto':auxp,'productos':prod,'edit':True})
    return render(request, 'products/my_products.html', {'usuario':u,'producto':p,'productos':prod,'edit':True})
def get_product_price(request):
    id_product = request.GET.get('id_product', None)
    product = Product.objects.get(id=id_product)
    complete = CompleteProduct.objects.filter(id_product = product, activo=True, id_price__in = Price.objects.filter(id_product=product,activo=True))
    complete = complete.order_by('id_unidad')
    data = {
        'id_product': id_product,
        'id_unidad': [],
        'id_precio': [],
        'unidad': [],
        'precio': [],
    }
    for comp in complete:
        data['id_unidad'].append(comp.id_unidad.id)
        data['id_precio'].append(comp.id_price.id)
        data['unidad'].append(UnidadDeMedida.objects.get(id=comp.id_unidad.id).abreviacion + ' - ' + UnidadDeMedida.objects.get(id=comp.id_unidad.id).nombre)
        data['precio'].append(Price.objects.get(id=comp.id_price.id).cantidad)
    return JsonResponse(data)

def check_unidad(request):
    id_product = request.GET.get('id_product', None)
    product = Product.objects.get(id=id_product)
    unidadesTotal = UnidadDeMedida.objects.all()
    unidades = CompleteProduct.objects.filter(id_product=product, activo = True)
    data = {
        'id_product': id_product,
        'unidadesTotal': [],
        'unidades': [],
    }
    for uni in unidadesTotal:
        data['unidadesTotal'].append(uni.id)
    for uni in unidades:
        data['unidades'].append(uni.id_unidad.id)
    print(data)
    return JsonResponse(data)

def add_price(request):
    id_product = request.GET.get('id_product', None)
    id_unidad = request.GET.get('id_unidad', None)
    cantidad = request.GET.get('cantidad', None)
    product = Product.objects.get(id=id_product)
    unidad = UnidadDeMedida.objects.get(id=id_unidad)
    price = Price(id_product=product, fecha_inicio = timezone.now(),cantidad = cantidad, activo=True)
    price.save()
    complete = CompleteProduct(id_product=product,id_unidad=unidad,id_price=price,activo=True)
    complete.save()
    data = { 'success': True,}
    return JsonResponse(data)
def save_price(request):
    id_product = request.GET.get('id_product', None)
    id_unidad = request.GET.get('id_unidad', None)
    cantidad = request.GET.get('cantidad', None)
    product = Product.objects.get(id=id_product)
    unidad = UnidadDeMedida.objects.get(id=id_unidad)
    complete = CompleteProduct.objects.get(id_product=product,id_unidad=unidad,activo=True)
    price = Price.objects.get(id = complete.id_price.id)
    price.fecha_final = timezone.now()
    price.activo = False
    price.save()
    newPrice = Price(id_product=product, fecha_inicio=timezone.now(), cantidad=cantidad, activo=True)
    newPrice.save()
    complete.id_price = newPrice
    complete.save()
    data = { 'success': True,}
    return JsonResponse(data)
def delete_price(request):
    id_product = request.GET.get('id_product', None)
    id_unidad = request.GET.get('id_unidad', None)
    product = Product.objects.get(id=id_product)
    unidad = UnidadDeMedida.objects.get(id=id_unidad)
    complete = CompleteProduct.objects.get(id_product=product,id_unidad=unidad,activo=True)
    price = Price.objects.get(id = complete.id_price.id)
    price.fecha_final = timezone.now()
    price.activo = False
    complete.activo = False
    price.save()
    complete.save()
    data = { 'success': True,}
    return JsonResponse(data)


def get_product_equiv(request):
    id_product = request.GET.get('id_product', None)
    product = Product.objects.get(id=id_product)
    complete_products = CompleteProduct.objects.filter(id_product=product, activo=True)
    unidades = UnidadDeMedida.objects.all()
    equiv = Equivalencias.objects.filter(id_product = product, activo=True).order_by('id_unidad_origen')
    data = {
        'id_equiv': [],
        'id_unidad_origen': [],

ocs/products/templates/products/my_products.html
{% extends "provider/home.html" %}

{% block content %}
<div class="clearfix">
  <h3 class="float-left">
    Catálogo de productos: <span data-toggle="help_code" title="En esta sección puedes consultar, registrar, desactivar y editar tus productos." class="fa fa-question-circle"></span>
  </h3>
  <h3 class="float-right nombre_producto">
  </h3>
</div>

<hr />
<!-- TABLA DE PRODUCTOS -->
<div class="row">
  <div class="col-5">
    <div class="card">
      <div class="container">
        <table id="myTable" class="table table-hover">
          <thead class="thead-dark">
            <tr>
              <th scope="col">#</th>
              <th scope="col">Nombre</th>
              <th scope="col">Código</th>
              <th scope="col" data-toggle="help_code" title="Desactiva tus productos para que no sean visibles para tus clientes.">Activo</th>
              <th scope="col">Editar</th>
            </tr>
          </thead>
          <tbody>
            {% for Producto in productos %}
            <tr>
              <td scope="row">{{ Producto.id }}</td>
              <th>{{ Producto.nombre.capitalize }}</th>
              <td>{{ Producto.codigo }}</td>
              <td class="text-center" id="ableUnable{{ Producto.id }}">
                {% if Producto.activo %}
                <div style="color:green" onclick="ableUnable({{ Producto.id }})">
                  <span class="fa fa-eye"></span>
                </div>
                {% else %}
                <div style="color:red" onclick="ableUnable({{ Producto.id }})">
                  <span class="fa fa-eye-slash"></span>
                </div>
                {% endif %}
              </td>
              <td class="text-center">
                <button type="button" class="btn" name="button" onclick="editProduct({{Producto.id}})" data-toggle="tooltip" data-placement="left" title="Editar información de {{ Producto.nombre }}">
                  <span class="fa fa-edit"></span>
                </button>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <!-- SECCION PARA EDITAR Y AGREGAR PRODUCTOS -->
  <div class="col">
    <div class="card text-center">
      <div class="card-body">
        <div class="clearfix">
          <h6 class="float-left">Información general: <b class="nombre_producto"></b></h6>
          <button type="button" class="btn btn-primary float-right" onclick="showAgregar()">
            <span class="fa fa-plus align-middle" style="font-size:18px"></span> Nuevo producto
          </button>
        </div>
        <hr />
        <div id="editar_producto" class="">
          <div id="no_selected" class="" style="color:gray">
            <br />
            <span class="fa fa-edit"></span> Selecciona un producto para editarlo
            <br /><br />
          </div>
          <div id="selected" class="text-left" hidden>
            <form action="{% url 'products:edit' %}" method="post">
              {% csrf_token %}
              <input required id="id_product" name="id_product" type="number" hidden>
              <div class="row pb-2">
                <div class="col-6">
                  <label for="nombre">Nombre:</label>
                  <input required id="nombre" name="nombre" type="text" class="form-control" placeholder="producto" max_length=100>
                  <label for="codigo">Código:</label>
                  <input required id="codigo" name="codigo" type="text" class="form-control" placeholder="CODIG123" max_length=10>
                  <div class="" hidden>
                    <label for="activo">Activo:</label>
                    <input id="activo" name="activo" type="checkbox" class="form-control" checked>
                  </div>
                </div>
                <div class="col-6">
                  <label for="descripcion">Descripción:</label>
                  <textarea required id="descripcion" name="descripcion" type="text" class="form-control" placeholder="descripción del producto" max_length=200 rows="4"></textarea>
                </div>
              </div>
              <center>
                <div class="btn-group" role="group" aria-label="Basic example">
                  <button type="button" class="btn btn-danger" onclick="cancelEdit()">Cancelar</button>
                  <button type="submit" class="btn btn-success">Actualizar información</button>
                </div>
              </center>
            </form>
          </div>
        </div>
        <div id="agregar_producto" class="text-left" hidden>
          <form action="{% url 'products:register' %}" method="post">
            {% csrf_token %}
            <div class="row pb-2">
              <div class="col-6">
                <label for="nombre">Nombre:</label>
                <input required id="nombre" name="nombre" type="text" class="form-control" placeholder="producto" max_length=100>
                <label for="codigo">Código:</label>
                <input required id="codigo" name="codigo" type="text" class="form-control" placeholder="CODIG123" max_length=10>
                <div class="" hidden>
                  <label for="activo">Activo:</label>
                  <input id="activo" name="activo" type="checkbox" class="form-control" checked>
                </div>
              </div>
              <div class="col-6">
                <label for="descripcion">Descripción:</label>
                <textarea required id="descripcion" name="descripcion" type="text" class="form-control" placeholder="descripción del producto" max_length=200 rows="4"></textarea>
              </div>
            </div>
            <hr />
            <div class="row pb-2">
              <div class="col-6">
                <label for="unidad_medida">Unidad de medida inicial: <span data-toggle="help_code" title="Esta se utilizara como la unidad de medida base para tu producto." class="fa fa-question-circle"></span></label>
                <select required class="form-control" id="unidad_medida" name="unidad_medida" onclick="if (this.value==0){this.value=1;}">
                  <option value="0" disabled selected>Selecciona una unidad</option>
                  {% for Unidad in unidad %}
                  <option value="{{Unidad.id}}">{{Unidad.abreviacion}} - {{Unidad.nombre}}</option>
                  {% endfor %}
                </select>
              </div>
              <div class="col-6">
                <label for="precio">Precio:</label>
                <input required id="precio" name="precio" placeholder="0,00" type="number" class="form-control" min="0" step="0.01">
              </div>
            </div>
            <center>
              <div class="btn-group" role="group" aria-label="Basic example">
                <button type="button" class="btn btn-danger" onclick="cancelAgregar()">Cancelar</button>
                <button type="submit" class="btn btn-success">Agregar producto</button>
              </div>
            </center>
          </form>
        </div>
      </div>
    </div>
    <hr />
    <!-- SECCION DE PRECIOS POR UNIDAD DE MEDIDA -->
    <div class="card">
      <div class="card-body">
        <h6>Precio por unidad de medida: <b class="nombre_producto"></b> <span data-toggle="help_code" title="Registra los diferentes precios por unidad de medida de tus productos o simplemente un precio con sus diferentes equivalencias." class="fa fa-question-circle"></span></h6>
        <hr />
        <div id="no_selected_price" class="text-center" style="color:gray">
          <br />
          <span class="fa fa-edit"></span> Selecciona un producto para ver sus precios
          <br /><br />
        </div>
        <div id="adding_price" class="text-center" style="color:gray" hidden>
          <br />
          <span class="fa fa-plus"></span> Agrega el producto para poder agregar más precios por unidad de medida
          <br /><br />
        </div>
        <div id="selected_price" class="" hidden>
          <input required id="id_product" name="id_product" type="number" hidden>
          <div id="precios_de_producto" class="row">
          </div>
          <div class="row">
            <div class="col-5">
              <select required class="form-control" id="unidad_de_medida" onclick="checaUnidad();">
                <option value="0" disabled selected>Selecciona una unidad</option>
                {% for Unidad in unidad %}
                <option value="{{Unidad.id}}" id="optuni{{Unidad.id}}">{{Unidad.abreviacion}} - {{Unidad.nombre}}</option>
                {% endfor %}
              </select>
            </div>
            <div class="col-5">
              <input required id="price" name="price" placeholder="0.00"type="number" class="form-control" min="0" step="0.01">
            </div>
            <div class="col-2 align-self-center">
              <button type="button" class="btn btn-sm btn-success" name="button" onclick="addPrice()">
                <span class="fa fa-plus"></span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
    <hr />
    <!-- SECCION DE EQUIVALENCIAS ENTRE UNIDADES DE MEDIDA -->
    <div class="card">
      <div class="card-body">
        <h6>Equivalencias: <b class="nombre_producto"></b> <span data-toggle="help_code" title="Las equivalencias sirven para que tus clientes puedan pedir tu producto en diferentes presentaciones con un solo precio registrado." class="fa fa-question-circle"></span></h6>
        <hr />
        <div id="no_selected_equiv" class="text-center" style="color:gray">
          <br />
          <span class="fa fa-edit"></span> Selecciona un producto para ver sus equivalencias
          <br /><br />
        </div>
        <div id="adding_equiv" class="text-center" style="color:gray" hidden>
          <br />
          <span class="fa fa-plus"></span> Agrega el producto para poder definir sus equivalencias
          <br /><br />
        </div>
        <div id="selected_equiv" class="" hidden>
          <input required id="id_product" name="id_product" type="number" hidden>

          <div class="row">
            <div class="col-7 row form-group">
              <div class="col-4 pt-2" onclick="document.getElementById('cantidad_origen').disabled=false;">
                <input disabled required id="cantidad_origen" placeholder="0.00" type="number" class="form-control" value="1" min="0" step="0.01">
              </div>
              <div class="col-4 pt-2">
                <select required class="form-control" id="unidad_origen" onchange="checkEquivDestino(this.value)">
                  <option value="0" disabled selected>Unidad:</option>
                  {% for Unidad in unidad %}
                  <option value="{{Unidad.id}}" id="optuniorg{{Unidad.id}}">{{Unidad.abreviacion}}</option>
                  {% endfor %}
                </select>
              </div>
              <div class="col-4 pt-2">
                de <b class="nombre_producto"></b> ...
              </div>
              <div class="col-4 pt-1">
                ... equivale a:
              </div>
              <div class="col-4 pt-1">
                <input required id="cantidad_destino" name="" placeholder="0.00" type="number" class="form-control" min="0" step="0.01">
              </div>
              <div class="col-4 pt-1">
                <select disabled required class="form-control" id="unidad_destino">
                  <option value="0" disabled selected>Unidad:</option>
                  {% for Unidad in unidad %}
                  <option value="{{Unidad.id}}" id="optunidest{{Unidad.id}}">{{Unidad.abreviacion}}</option>
                  {% endfor %}
                </select>
              </div>
              <div class="col-12 pt-2">
                <div class="col text-center">
                  <button type="button" class="btn btn-sm btn-success" name="button" onclick="registrarEquivalencia()">
                    Registrar equivalencia
                  </button>
                </div>
              </div>
            </div>
            <div class="col-5">
              <div class="card text-center" >
                <ul id="equivalencias_de_producto" class="list-group list-group-flush">
                  <br />
                  <p style="color:gray">
                    Aún no registras ninguna equivalencia
                  </p>
                  <br /><br />
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
$(document).ready(function(){
    $('[data-toggle="help_code"]').tooltip();
});
</script>
{% endblock content %}




























<!---->